DROP TABLE castings;
DROP TABLE stars;
DROP TABLE movies;

CREATE TABLE movies (
  id SERIAL8 PRIMARY KEY,
  title TEXT VARCHAR(255),
  genre TEXT VARCHAR(255)
);

CREATE TABLE stars (
  id SERIAL8 PRIMARY KEY,
  first_name TEXT VARCHAR(255),
  last_name TEXT VARCHAR(255)
);

CREATE TABLE castings (
  id SERIAL8 PRIMARY KEY,
  movie_id INT2 REFERENCES movies(id) ON DELETE CASCADE,
  star_id INT2 REFERENCES stars(id) ON DELETE CASCADE,
  fee INT2
);
